Admin.create!(
  email: 'ouchi@ouchi',
  password: 'oooooo',
)

users = User.create!(
  [
    {email: 'ren@test.com', name: '蓮', password: 'password', profile_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-user1.jpg"), filename:"sample-user1.jpg")},
    {email: 'tsumugi@test.com', name: 'つむぎ', password: 'password', profile_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-user2.jpg"), filename:"sample-user2.jpg")},
    {email: 'himari@test.com', name: 'ひまり', password: 'password', profile_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-user3.jpg"), filename:"sample-user3.jpg")},
    {email: 'mei@test.com', name: 'めい', password: 'password', profile_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-user5.jpg"), filename:"sample-user5.jpg")},
    {email: 'mio@test.com', name: '陽葵', password: 'password', profile_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-user6.jpg"), filename:"sample-user6.jpg")},
    {email: 'riko@test.com', name: 'Riko', password: 'password', profile_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-user7.jpg"), filename:"sample-user7.jpg")},
    {email: 'an@test.com', name: '杏', password: 'password', profile_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-user9.jpg"), filename:"sample-user9.jpg")},
    {email: 'akari@test.com', name: 'あかり', password: 'password', profile_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-user10.jpg"), filename:"sample-user10.jpg")},
    {email: 'miyu@test.com', name: 'Miyuu', password: 'password', profile_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-user13.jpg"), filename:"sample-user13.jpg")},
    {email: 'ayumi@test.com', name: 'あゆみ', password: 'password', profile_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-user14.jpg"), filename:"sample-user14.jpg")}
  ]
)

post_recipes = PostRecipe.create!(
  [
    {title: 'ぶり大根', recipe_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/buridaikon.jpg"), filename:"buridaikon.jpg"), serving: '4人分', advice: '特にありません。', is_draft: 'false', user_id: users[1].id },
    {title: '親子丼', recipe_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/oyakodon.jpg"), filename:"oyakodon.jpg"), serving: '4人分', advice: '特にありません。', is_draft: 'false', user_id: users[1].id },
    {title: '簡単コーンスープ', recipe_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/pota-ju.jpg"), filename:"pota-ju.jpg"), serving: '4人分', advice: '特にありません。', is_draft: 'false', user_id: users[1].id },
    {title: 'ポテトサラダ', recipe_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/potetosarada.jpg"), filename:"potetosarada.jpg"), serving: '4人分', advice: '特にありません。', is_draft: 'false', user_id: users[1].id },
    {title: 'オムレツ', recipe_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/omuretsu.jpg"), filename:"omuretsu.jpg"), serving: '4人分', advice: '特にありません。', is_draft: 'false', user_id: users[1].id },
    {title: 'マーボー豆腐', recipe_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/ma-bo-tofu.jpg"), filename:"ma-bo-tofu.jpg"), serving: '4人分', advice: '特にありません。', is_draft: 'false', user_id: users[3].id },
    {title: '肉じゃが', recipe_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/nikujaga.jpg"), filename:"nikujaga.jpg"), serving: '4人分', advice: '特にありません。', is_draft: 'false', user_id: users[3].id },
    {title: 'プルコギ', recipe_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/purukogi.jpg"), filename:"purukogi.jpg"), serving: '4人分', advice: '特にありません。', is_draft: 'false', user_id: users[3].id },
    {title: 'ギョーザ', recipe_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/gyo-za.jpg"), filename:"gyo-za.jpg"), serving: '4人分', advice: '特にありません。', is_draft: 'false', user_id: users[3].id },
    {title: 'さばの味噌煮', recipe_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sabanomisoni.jpg"), filename:"sabanomisoni.jpg"), serving: '4人分', advice: '特にありません。', is_draft: 'false', user_id: users[4].id },
    {title: '茶碗蒸し', recipe_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/tyawanmushi.jpg"), filename:"tyawanmushi.jpg"), serving: '4人分', advice: '特にありません。', is_draft: 'false', user_id: users[3].id },
    {title: 'キャベツの丸ごと煮', recipe_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/potofu.jpg"), filename:"potofu.jpg"), serving: '4人分', advice: '特にありません。', is_draft: 'false', user_id: users[2].id },
    {title: '豚汁', recipe_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/tonjiru.jpg"), filename:"tonjiru.jpg"), serving: '4人分', advice: '特にありません。', is_draft: 'false', user_id: users[2].id },
    {title: 'ハンバーグ',recipe_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/hanba-gu.jpg"), filename:"hanba-gu.jpg"), serving: '4人分', advice: '特にありません。', is_draft: 'false', user_id: users[1].id },
    {title: 'グラタン', recipe_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/guratan.jpg"), filename:"guratan.jpg"), serving: '4人分', advice: 'マカロニは別ゆでせず、ソースに直接加えてOK！', is_draft: 'false', user_id: users[1].id }
 ]
)

MakingRecipe.create!(
  [
    {recipe: '①ぶりは１切れを３～４つに切る。', post_recipe_id: post_recipes[0].id },
    {recipe: '②大根は２㎝厚さのいちょう切りにし、皮を厚めにむく。', post_recipe_id: post_recipes[0].id },
    {recipe: '③フライパンにAを煮立て、大根を入れて中火弱で７～８分煮る。', post_recipe_id: post_recipes[0].id },
    {recipe: '④③にぶりを加えて落しぶたをし、７～８分煮る。', post_recipe_id: post_recipes[0].id },
    {recipe: '①鶏肉は１㎝角、玉ねぎは薄い半月切りにする。万能ねぎは３㎝長さに切る。卵はボウルに割りほぐす。', post_recipe_id: post_recipes[1].id },
    {recipe: '②２人分ずつ作る。小さめのフライパンにＡの半量を入れて中火にかけ、煮立ったら鶏肉を半量加える。鶏肉を返して玉ねぎを半量加え、火が通るまで煮る。', post_recipe_id: post_recipes[1].id },
    {recipe: '③溶き卵の半量を回し入れ、すぐにふたをして強火で15秒、ときどき鍋を揺すりながら蒸し煮にする。ふたを取って万能ねぎを散らし、火を止める。', post_recipe_id: post_recipes[1].id },
    {recipe: '④器にごはんを盛り、③をのせる。残りも同様に作る。', post_recipe_id: post_recipes[1].id },
    {recipe: '①鍋にＡを煮立て、塩、こしょうをふる。', post_recipe_id: post_recipes[2].id },
    {recipe: '②Ｂを溶いて①に回し入れて、とろみをつける。バターを加え、Ｃを散らす。', post_recipe_id: post_recipes[2].id },
    {recipe: '①じゃがいもは皮をむいて乱切り、にんじんは皮をむいて薄いいちょう切りにし、一緒に水からやわらかくゆで、ざるにあげる。', post_recipe_id: post_recipes[3].id },
    {recipe: '②玉ねぎは縦薄切り、きゅうりは薄い輪切りにして塩少量をふる。', post_recipe_id: post_recipes[3].id },
    {recipe: '③ボウルにじゃがいもを入れてつぶし、にんじん、玉ねぎを加えて、熱いうちにドレッシングをかける。', post_recipe_id: post_recipes[3].id },
    {recipe: '④粗熱が取れたら、マヨネーズ、水けを絞ったきゅうりを加え、塩少量、こしょうで味を調える。', post_recipe_id: post_recipes[3].id },
    {recipe: '①ボウルに卵を割りほぐし、Aを加えて混ぜる。', post_recipe_id: post_recipes[4].id },
    {recipe: '②フライパンにサラダ油小さじ1を熱してなじませ、火からはずして、①の1/4量とバター大さじ1弱を加え、ひと呼吸おいて中火弱にかける。', post_recipe_id: post_recipes[4].id },
    {recipe: '③菜箸でゆっくりと大きく混ぜ、半熟になり始めたら、手前から折って奥に寄せ、フライパンのふちを利用して形を作る。返しながら器に盛り、塩、黒こしょうを軽くふる。残り３つも同様に作る。', post_recipe_id: post_recipes[4].id },
    {recipe: '①豆腐は2㎝角に切り、ペーパータオルを敷いた耐熱皿に並べる。ラップをかけ、電子レンジ（500Ｗ）で３分加熱して水きりをする。', post_recipe_id: post_recipes[5].id },
    {recipe: '②ねぎ、にんにくはみじん切りにする。Ａは混ぜ合わせる。', post_recipe_id: post_recipes[5].id },
    {recipe: '③フライパンにサラダ油、ねぎ、にんにく、豆板醬を入れて中火で熱し、香りが出たら、ひき肉を加えてポロポロに炒める。', post_recipe_id: post_recipes[5].id },
    {recipe: '④Ａを加えてひと煮立ちさせ、①の豆腐を加える。', post_recipe_id: post_recipes[5].id },
    {recipe: '⑤豆腐が温まったら端に寄せ、煮汁にＢの水溶き片栗粉を加えてとろみをつけ、ごま油を加える。器に盛り、粉山椒をふる。', post_recipe_id: post_recipes[5].id },
    {recipe: '①豚肉は4～5㎝長さに切る。', post_recipe_id: post_recipes[6].id },
    {recipe: '②じゃがいもは皮をむいて4つ割りにし、水に10分さらして水けをふく。', post_recipe_id: post_recipes[6].id },
    {recipe: '③にんじんは皮をむき、太い部分は縦4つ割り、細い部分は縦2つ割りにし、1.5㎝幅に切る。', post_recipe_id: post_recipes[6].id },
    {recipe: '④玉ねぎは縦8つ割りにする。', post_recipe_id: post_recipes[6].id },
    {recipe: '⑤しらたきは3～4㎝長さに切り、塩もみをして水で洗う。鍋に入れ、水をひたひたに加えて煮立て、火を弱めて5分ゆで、ざるにあげる。', post_recipe_id: post_recipes[6].id },
    {recipe: '⑥フライパンにサラダ油を熱し、豚肉を中火でほくじながら炒める。', post_recipe_id: post_recipes[6].id },
    {recipe: '⑦肉の色が変わったらじゃがいも、にんじん、玉ねぎを炒め合わせる。。', post_recipe_id: post_recipes[6].id },
    {recipe: '⑧酒をふり、水カップ2/3～1を加えて煮立て、Ａで調味する。ふたをして、弱火で8～10分煮る。', post_recipe_id: post_recipes[6].id },
    {recipe: '⑨しょうゆを加え、再びふたをして6～8分煮る。', post_recipe_id: post_recipes[6].id },
    {recipe: '①牛肉は大きければ4～5㎝長さに切る。ボウルに入れ、Aをもみ込み、20～30分漬ける。', post_recipe_id: post_recipes[7].id },
    {recipe: '②にんじんは皮をむいて、ピーラーで薄いリボン状に切る。豆もやしは好みでひげ根を取る。', post_recipe_id: post_recipes[7].id },
    {recipe: '③フライパンを熱し、①を入れて、ほぐすように炒める。肉の色が変わったら②を加え、しんなりするまで炒めて、白ごまをふる。', post_recipe_id: post_recipes[7].id },
    {recipe: '①白菜はみじん切りにしてボウルに入れ、塩をふって混ぜる。しんなりするまで約20分おき、水けを絞る。にらはみじん切りにする。', post_recipe_id: post_recipes[8].id },
    {recipe: '②ボウルにひき肉、ねぎ、Aを入れ、よく混ぜ合わせる。①を加え、さらによく混ぜる。', post_recipe_id: post_recipes[8].id },
    {recipe: '③ギョーザの皮に②を大さじ1弱のせる。皮のふちに水を塗り、ひだを作りながら包み込む。ペーパータオルを敷いたバットに並べる。', post_recipe_id: post_recipes[8].id },
    {recipe: '④フライパンにサラダ油大さじ1・1/2～2を中火で熱し、③の1/2量を並べて色よく焼く。水カップ1/2～2をギョーザの高さの1/2まで注ぎ、ふたをして、水けがなくなるまで4～5分弱火で蒸し焼きにする。', post_recipe_id: post_recipes[8].id },
    {recipe: '①さばは半身を２つに切り、皮に浅く十文字の切り込みを入れる。', post_recipe_id: post_recipes[9].id },
    {recipe: '②しょうがは千切りにする。', post_recipe_id: post_recipes[9].id },
    {recipe: '③ごぼうは洗い、8～10㎝の長さに切って縦4～6つ割りにし、水に約5分さらす。', post_recipe_id: post_recipes[9].id },
    {recipe: '④ごぼうの水気をきり、ひたひたの水とともに鍋に入れて煮立て、ふたをして弱火で10～15分ゆでる。やわらかくなったら、ざるにあげる。', post_recipe_id: post_recipes[9].id },
    {recipe: '⑤フライパンにAを煮立て、しょうがを加える。再び煮立ったら、さばを重ならないように入れ、煮汁をスプーンでかける。', post_recipe_id: post_recipes[9].id },
    {recipe: '⑥さばの表面の色が変わったら、アルミ箔の落しぶたをし、さらにフライパンのふたもして、弱火で約10分煮る。', post_recipe_id: post_recipes[9].id },
    {recipe: '⑦さばを端に寄せてごぼうを加え、ふたをして3～4分煮る。', post_recipe_id: post_recipes[9].id },
    {recipe: '⑧みそを小さいボウルに入れ、煮汁で溶きのばしてフライパンに加え、再びふたをして約5分煮る。', post_recipe_id: post_recipes[9].id },
    {recipe: '①ささ身は薄いそぎ切りにする。えびは背わた、尾、殻を取り、ささ身と合わせてＢをまぶす。', post_recipe_id: post_recipes[10].id },
    {recipe: '②しいたけは軸を取って薄切り、かまぼこも薄切りにする。ぎんなんは殻から出し、熱湯で3分ほどゆでて水にとり、薄皮をむく。', post_recipe_id: post_recipes[10].id },
    {recipe: '③ボウルに卵を割りほぐし、Ａを加えてよく混ぜ、目の細かいざるでこす。', post_recipe_id: post_recipes[10].id },
    {recipe: '④耐熱容器に①と②を入れ、③を静かに注いで、表面に泡が浮いたら竹串でつぶす。', post_recipe_id: post_recipes[10].id },
    {recipe: '⑤沸騰した蒸し器に④を入れ、ふきんでくるんだふたをかぶせて、強火で約１分蒸し、弱火にして約１５分蒸す。竹串を刺して、澄んだ汁が出てくれば蒸し上がり。。', post_recipe_id: post_recipes[10].id },
    {recipe: '①キャベツは芯をくりぬいて、８等分のくし形に切る。玉ねぎは縦薄切り、にんじんは皮をむき、４～５㎝長さに切って縦４つ割りにする。', post_recipe_id: post_recipes[11].id },
    {recipe: '②鍋に①とソーセージ、Ａを入れて火にかける。', post_recipe_id: post_recipes[11].id },
    {recipe: '③煮立ったらふたをし、弱火で１５～２０分煮て、塩、こしょうで味を調える。', post_recipe_id: post_recipes[11].id },
    {recipe: '①大根、にんじんは皮をむいていちょう切りにする。ごぼうはささがきにして水にさらす。こんにゃくはさっとゆで、短冊切りにする。', post_recipe_id: post_recipes[12].id },
    {recipe: '②鍋にサラダ油を熱して豚肉を炒め、①を加えて炒め合わせ、酒をふる。', post_recipe_id: post_recipes[12].id },
    {recipe: '③Ａを加え、煮立ったら、アクを取りながら弱火で約10分煮る。', post_recipe_id: post_recipes[12].id },
    {recipe: '④みそを煮汁で溶きのばして加え、ねぎも加えてひと煮立ちする。器に盛り、七味とうがらしをふる。', post_recipe_id: post_recipes[12].id },
    {recipe: '①玉ねぎはみじん切りにして耐熱容器に入れ、サラダ油大さじ１を加えて混ぜる。ラップをふんわりとかけ、電子レンジ（600W）で6分加熱。取り出して混ぜ、粗熱を取る。', post_recipe_id: post_recipes[13].id },
    {recipe: '②にんじんは皮をむいて1㎝幅の輪切り、ブロッコリーは小房に分け、いずれも塩ゆでする。', post_recipe_id: post_recipes[13].id },
    {recipe: '③ボウルにひき肉、A、①を入れ、粘りが出るまで練る。肉だねを手に取り、ボウルに数回たたきつけて空気を抜き、4等分の小判形に整えて、真ん中を少しくぼませる。', post_recipe_id: post_recipes[13].id },
    {recipe: '④フライパンにサラダ油大さじ１を強火で熱して③を入れ、両面を1～2分ずつこんがりと焼く。', post_recipe_id: post_recipes[13].id },
    {recipe: '⑤フライパンのあいている場所に混ぜ合わせたBを入れ、ふたをして弱火で10～12分ほど蒸し焼きにする。器にハンバーグを②を盛り、フライパンに残ったソースをかける。', post_recipe_id: post_recipes[13].id },
    {recipe: '①えびは背わたがあれば取る。', post_recipe_id: post_recipes[14].id },
    {recipe: '②マッシュルームは石づきを除いて5㎜厚さに切り、玉ねぎは縦薄切りにする。', post_recipe_id: post_recipes[14].id },
    {recipe: '③フライパンにバターを中火で熱し、半ば溶けたら玉ねぎを入れてしんなりと炒める。マッシュルームを加えて炒め、小麦粉をふって粉けがなくなるまで炒める。', post_recipe_id: post_recipes[14].id },
    {recipe: '④Ａを加え、強火にして、混ぜながらとろみがつくまで火にかける。マカロニを加えて混ぜ、ふたをして、弱火で袋の表示時間どおりに煮る。', post_recipe_id: post_recipes[14].id },
    {recipe: '⑤牛乳を加えて混ぜ、えびを加えて中火にし、フツフツしてきたら、ふたをして弱火で5分煮る。', post_recipe_id: post_recipes[14].id },
    {recipe: '⑥⑤をグラタン皿に入れてチーズをふり、オーブントースターで10～15分焼く。', post_recipe_id: post_recipes[14].id }
  ]
)

Ingredient.create!(
  [
    {food_name: 'ぶり', amount: '3', unit: '切れ', other_amount: '', post_recipe_id: post_recipes[0].id },
    {food_name: '大根', amount: '0.5', unit: '本', other_amount: '', post_recipe_id: post_recipes[0].id },
    {food_name: '酒', amount: '100', unit: '㎖', other_amount: 'A:（1/2カップ）', post_recipe_id: post_recipes[0].id },
    {food_name: '砂糖', amount: '3', unit: '', other_amount: 'A:大さじ', post_recipe_id: post_recipes[0].id },
    {food_name: 'しょうゆ', amount: '4', unit: '', other_amount: 'A:大さじ', post_recipe_id: post_recipes[0].id },
    {food_name: '水', amount: '400', unit: '㎖', other_amount: 'A:（2カップ）', post_recipe_id: post_recipes[0].id },
    {food_name: '温かいごはん', amount: '', unit: '', other_amount: '適量', post_recipe_id: post_recipes[1].id },
    {food_name: '鶏もも肉', amount: '1', unit: '枚', other_amount: '大', post_recipe_id: post_recipes[1].id },
    {food_name: '玉ねぎ', amount: '1', unit: '個', other_amount: '', post_recipe_id: post_recipes[1].id },
    {food_name: '万能ねぎ', amount: '10', unit: '本', other_amount: '', post_recipe_id: post_recipes[1].id },
    {food_name: '卵', amount: '6', unit: '個', other_amount: 'カップ２', post_recipe_id: post_recipes[1].id },
    {food_name: 'Ａ：だし', amount: '', unit: '', other_amount: '', post_recipe_id: post_recipes[1].id },
    {food_name: 'Ａ：みりん', amount: '', unit: '', other_amount: 'カップ1/2', post_recipe_id: post_recipes[1].id },
    {food_name: 'Ａ：しょうゆ', amount: '', unit: '', other_amount: 'カップ1/2', post_recipe_id: post_recipes[1].id },
    {food_name: 'Ａ：砂糖', amount: '', unit: '', other_amount: '小さじ2', post_recipe_id: post_recipes[1].id },
    {food_name: 'Ａ:クリームコーン缶', amount: '1', unit: '缶', other_amount: '', post_recipe_id: post_recipes[2].id },
    {food_name: 'Ａ：固形スープの素', amount: '1', unit: '個', other_amount: '', post_recipe_id: post_recipes[2].id },
    {food_name: 'Ａ：水', amount: '', unit: '', other_amount: 'カップ1', post_recipe_id: post_recipes[2].id },
    {food_name: 'Ａ：牛乳', amount: '', unit: '', other_amount: 'カップ1・1/2', post_recipe_id: post_recipes[2].id },
    {food_name: '塩', amount: '', unit: '', other_amount: '少量', post_recipe_id: post_recipes[2].id },
    {food_name: 'こしょう', amount: '', unit: '', other_amount: '少量', post_recipe_id: post_recipes[2].id },
    {food_name: 'Ｂ：コーンスターチ', amount: '', unit: '', other_amount: '大さじ1', post_recipe_id: post_recipes[2].id },
    {food_name: 'Ｂ：水', amount: '', unit: '', other_amount: '大さじ1', post_recipe_id: post_recipes[2].id },
    {food_name: 'バター', amount: '', unit: '', other_amount: '小さじ2', post_recipe_id: post_recipes[2].id },
    {food_name: 'Ｃ（あれば）：クラッカー', amount: '', unit: '', other_amount: '適量', post_recipe_id: post_recipes[2].id },
    {food_name: 'Ｃ（あれば）：パセリ（みじん切り）', amount: '', unit: '', other_amount: '適量', post_recipe_id: post_recipes[2].id },
    {food_name: 'じゃがいも', amount: '4', unit: '個', other_amount: '', post_recipe_id: post_recipes[3].id },
    {food_name: 'にんじん', amount: '', unit: '本', other_amount: '1/4', post_recipe_id: post_recipes[3].id },
    {food_name: '玉ねぎ', amount: '', unit: '個', other_amount: '1/4', post_recipe_id: post_recipes[3].id },
    {food_name: 'きゅうり', amount: '1', unit: '本', other_amount: '', post_recipe_id: post_recipes[3].id },
    {food_name: 'フレンチドレッシング', amount: '', unit: '', other_amount: '大さじ２', post_recipe_id: post_recipes[3].id },
    {food_name: 'マヨネーズ', amount: '', unit: '', other_amount: '大さじ4～5', post_recipe_id: post_recipes[3].id },
    {food_name: '塩', amount: '', unit: '', other_amount: '適宜', post_recipe_id: post_recipes[3].id },
    {food_name: 'こしょう', amount: '', unit: '', other_amount: '少量', post_recipe_id: post_recipes[3].id },
    {food_name: '卵', amount: '8', unit: '個', other_amount: '', post_recipe_id: post_recipes[4].id },
    {food_name: 'Ａ：塩', amount: '', unit: '', other_amount: '小さじ1/3', post_recipe_id: post_recipes[4].id },
    {food_name: 'Ａ：こしょう', amount: '', unit: '', other_amount: '少量', post_recipe_id: post_recipes[4].id },
    {food_name: 'サラダ油', amount: '', unit: '', other_amount: '小さじ4', post_recipe_id: post_recipes[4].id },
    {food_name: 'バター', amount: '', unit: '', other_amount: '大さじ4弱（40ｇ）', post_recipe_id: post_recipes[4].id },
    {food_name: '塩', amount: '', unit: '', other_amount: '適量', post_recipe_id: post_recipes[4].id },
    {food_name: '粗びき黒こしょう', amount: '', unit: '適量', other_amount: '', post_recipe_id: post_recipes[4].id },
    {food_name: '木綿豆腐', amount: '2', unit: '丁', other_amount: '（600ℊ）', post_recipe_id: post_recipes[5].id },
    {food_name: '豚ひき肉', amount: '150', unit: 'ℊ', other_amount: '', post_recipe_id: post_recipes[5].id },
    {food_name: 'ねぎ', amount: '1', unit: '本', other_amount: '（100ℊ）', post_recipe_id: post_recipes[5].id },
    {food_name: 'にんにく', amount: '1', unit: 'かけ', other_amount: '', post_recipe_id: post_recipes[5].id },
    {food_name: 'サラダ油', amount: '', unit: '', other_amount: '大さじ1強', post_recipe_id: post_recipes[5].id },
    {food_name: '水', amount: '', unit: '', other_amount: 'A:カップ1', post_recipe_id: post_recipes[5].id },
    {food_name: '鶏がらスープの素', amount: '', unit: '', other_amount: 'A:小さじ1/2', post_recipe_id: post_recipes[5].id },
    {food_name: '砂糖', amount: '', unit: '', other_amount: 'A:小さじ1', post_recipe_id: post_recipes[5].id },
    {food_name: '酒', amount: '', unit: '', other_amount: 'A:大さじ1', post_recipe_id: post_recipes[5].id },
    {food_name: 'しょうゆ', amount: '', unit: '', other_amount: 'A:大さじ1', post_recipe_id: post_recipes[5].id },
    {food_name: 'みそ', amount: '', unit: '', other_amount: 'A:大さじ1・1/2', post_recipe_id: post_recipes[5].id },
    {food_name: '豆板醬', amount: '', unit: '', other_amount: '小さじ1・1/2', post_recipe_id: post_recipes[5].id },
    {food_name: '片栗粉', amount: '', unit: '', other_amount: 'B:大さじ1', post_recipe_id: post_recipes[5].id },
    {food_name: '水', amount: '', unit: '', other_amount: 'B:大さじ1', post_recipe_id: post_recipes[5].id },
    {food_name: 'ごま油', amount: '', unit: '', other_amount: '大さじ1', post_recipe_id: post_recipes[5].id },
    {food_name: '（お好みで）粉山椒', amount: '', unit: '', other_amount: '少量', post_recipe_id: post_recipes[5].id },
    {food_name: '豚バラ薄切り肉', amount: '200', unit: 'ℊ', other_amount: '', post_recipe_id: post_recipes[6].id },
    {food_name: 'じゃがいも', amount: '5', unit: '個', other_amount: '大', post_recipe_id: post_recipes[6].id },
    {food_name: 'にんじん', amount: '1', unit: '本', other_amount: '大', post_recipe_id: post_recipes[6].id },
    {food_name: '玉ねぎ', amount: '1', unit: '個', other_amount: '', post_recipe_id: post_recipes[6].id },
    {food_name: 'しらたき', amount: '1', unit: '袋', other_amount: '', post_recipe_id: post_recipes[6].id },
    {food_name: 'サラダ油', amount: '', unit: '', other_amount: '大さじ1/2', post_recipe_id: post_recipes[6].id },
    {food_name: '酒', amount: '3', unit: '', other_amount: '大さじ', post_recipe_id: post_recipes[6].id },
    {food_name: 'みりん', amount: '2', unit: '', other_amount: 'Ａ：大さじ', post_recipe_id: post_recipes[6].id },
    {food_name: '砂糖', amount: '1', unit: '', other_amount: 'Ａ：大さじ', post_recipe_id: post_recipes[6].id },
    {food_name: 'しょうゆ', amount: '4', unit: '', other_amount: '大さじ', post_recipe_id: post_recipes[6].id },
    {food_name: '塩', amount: '200', unit: 'ℊ', other_amount: '適宜', post_recipe_id: post_recipes[6].id },
    {food_name: '牛切り落とし肉', amount: '300', unit: 'ℊ', other_amount: '', post_recipe_id: post_recipes[7].id },
    {food_name: 'A：酒', amount: '', unit: '', other_amount: '大さじ2', post_recipe_id: post_recipes[7].id },
    {food_name: 'A：しょうゆ', amount: '', unit: '', other_amount: '大さじ3', post_recipe_id: post_recipes[7].id },
    {food_name: 'A：ねぎ（みじん切り）', amount: '', unit: '', other_amount: '大さじ2', post_recipe_id: post_recipes[7].id },
    {food_name: 'A：にんにく（みじん切り）', amount: '', unit: '', other_amount: '小さじ1', post_recipe_id: post_recipes[7].id },
    {food_name: 'A：しょうが汁', amount: '', unit: '', other_amount: '少量', post_recipe_id: post_recipes[7].id },
    {food_name: 'A：砂糖', amount: '', unit: '', other_amount: '小さじ2', post_recipe_id: post_recipes[7].id },
    {food_name: 'A：一味とうがらし', amount: '', unit: '', other_amount: '少量', post_recipe_id: post_recipes[7].id },
    {food_name: 'A：ごま油', amount: '', unit: '', other_amount: '大さじ1', post_recipe_id: post_recipes[7].id },
    {food_name: 'にんじん', amount: '1', unit: '本', other_amount: '', post_recipe_id: post_recipes[7].id },
    {food_name: '豆もやし', amount: '1', unit: '袋', other_amount: '', post_recipe_id: post_recipes[7].id },
    {food_name: '白いりごま', amount: '', unit: '', other_amount: '小さじ1', post_recipe_id: post_recipes[7].id },
    {food_name: '豚ひき肉', amount: '250', unit: 'ℊ', other_amount: '', post_recipe_id: post_recipes[8].id },
    {food_name: '白菜', amount: '4', unit: '枚', other_amount: '（400ℊ）', post_recipe_id: post_recipes[8].id },
    {food_name: '塩', amount: '', unit: '', other_amount: '小さじ1', post_recipe_id: post_recipes[8].id },
    {food_name: 'にら', amount: '1', unit: '束', other_amount: '（100ℊ）', post_recipe_id: post_recipes[8].id },
    {food_name: 'ねぎ（みじん切り）', amount: '', unit: '', other_amount: '大さじ4', post_recipe_id: post_recipes[8].id },
    {food_name: 'A：しょうが汁', amount: '', unit: '', other_amount: '小さじ1', post_recipe_id: post_recipes[8].id },
    {food_name: 'A：砂糖', amount: '', unit: '', other_amount: '小さじ1', post_recipe_id: post_recipes[8].id },
    {food_name: 'A：酒', amount: '', unit: '', other_amount: '大さじ2', post_recipe_id: post_recipes[8].id },
    {food_name: 'A：しょうゆ', amount: '', unit: '', other_amount: '大さじ1/2', post_recipe_id: post_recipes[8].id },
    {food_name: 'A：こしょう', amount: '', unit: '', other_amount: '少量', post_recipe_id: post_recipes[8].id },
    {food_name: 'A：片栗粉', amount: '', unit: '', other_amount: '大さじ1', post_recipe_id: post_recipes[8].id },
    {food_name: 'A：ごま油', amount: '', unit: '', other_amount: '大さじ1', post_recipe_id: post_recipes[8].id },
    {food_name: 'ギョーザの皮', amount: '32', unit: '枚', other_amount: '大', post_recipe_id: post_recipes[8].id },
    {food_name: 'サラダ油', amount: '', unit: '', other_amount: '大さじ3～4', post_recipe_id: post_recipes[8].id },
    {food_name: 'しょうゆ', amount: '', unit: '', other_amount: '適量', post_recipe_id: post_recipes[8].id },
    {food_name: '酢', amount: '', unit: '', other_amount: '適量', post_recipe_id: post_recipes[8].id },
    {food_name: 'ラー油', amount: '', unit: '', other_amount: '適量', post_recipe_id: post_recipes[8].id },
    {food_name: 'さば（三枚おろし）', amount: '1', unit: '尾', other_amount: '大', post_recipe_id: post_recipes[9].id },
    {food_name: 'しょうが', amount: '', unit: '', other_amount: '1/2かけ', post_recipe_id: post_recipes[9].id },
    {food_name: 'ごぼう', amount: '1', unit: '本', other_amount: '', post_recipe_id: post_recipes[9].id },
    {food_name: '水', amount: '200', unit: '㎖', other_amount: 'A:（1カップ）', post_recipe_id: post_recipes[9].id },
    {food_name: '酒', amount: '3', unit: '', other_amount: 'A:大さじ', post_recipe_id: post_recipes[9].id },
    {food_name: 'みりん', amount: '2', unit: '', other_amount: 'A:大さじ', post_recipe_id: post_recipes[9].id },
    {food_name: '砂糖', amount: '2', unit: '', other_amount: 'A:大さじ', post_recipe_id: post_recipes[9].id },
    {food_name: 'しょうゆ', amount: '1', unit: '', other_amount: 'A:大さじ', post_recipe_id: post_recipes[9].id },
    {food_name: 'みそ', amount: '', unit: '', other_amount: '大さじ3～3・1/3(50～60ℊ)', post_recipe_id: post_recipes[9].id },
    {food_name: '卵', amount: '2', unit: '個', other_amount: '', post_recipe_id: post_recipes[10].id },
    {food_name: 'Ａ：だし', amount: '', unit: '', other_amount: 'カップ2', post_recipe_id: post_recipes[10].id },
    {food_name: 'Ａ：酒', amount: '', unit: '', other_amount: '小さじ1', post_recipe_id: post_recipes[10].id },
    {food_name: 'Ａ：薄口しょうゆ', amount: '', unit: '小さじ1', other_amount: '', post_recipe_id: post_recipes[10].id },
    {food_name: 'Ａ：塩', amount: '', unit: '', other_amount: '小さじ2/3', post_recipe_id: post_recipes[10].id },
    {food_name: '鶏ささ身', amount: '2', unit: '本', other_amount: '', post_recipe_id: post_recipes[10].id },
    {food_name: '殻つきえび', amount: '4', unit: '尾', other_amount: '', post_recipe_id: post_recipes[10].id },
    {food_name: 'Ｂ：酒', amount: '', unit: '', other_amount: '小さじ1', post_recipe_id: post_recipes[10].id },
    {food_name: 'Ｂ：塩', amount: '', unit: '', other_amount: '少量', post_recipe_id: post_recipes[10].id },
    {food_name: 'Ｂ：しょうゆ', amount: '', unit: '', other_amount: '小さじ1/2', post_recipe_id: post_recipes[10].id },
    {food_name: 'しいたけ', amount: '4', unit: '枚', other_amount: '小', post_recipe_id: post_recipes[10].id },
    {food_name: 'かまぼこ', amount: '40', unit: 'ℊ', other_amount: '', post_recipe_id: post_recipes[10].id },
    {food_name: 'ぎんなん', amount: '8', unit: '粒', other_amount: '', post_recipe_id: post_recipes[10].id },
    {food_name: 'キャベツ', amount: '1', unit: '個', other_amount: '', post_recipe_id: post_recipes[11].id },
    {food_name: '玉ねぎ', amount: '', unit: '', other_amount: '1/2個', post_recipe_id: post_recipes[11].id },
    {food_name: 'にんじん', amount: '1', unit: '本', other_amount: '大', post_recipe_id: post_recipes[11].id },
    {food_name: 'ウインナー', amount: '12', unit: '本', other_amount: '', post_recipe_id: post_recipes[11].id },
    {food_name: 'Ａ：水', amount: '', unit: '', other_amount: 'カップ3', post_recipe_id: post_recipes[11].id },
    {food_name: 'Ａ：固形スープの素', amount: '2', unit: '個', other_amount: '', post_recipe_id: post_recipes[11].id },
    {food_name: 'Ａ：ローリエ', amount: '1', unit: '枚', other_amount: '', post_recipe_id: post_recipes[11].id },
    {food_name: '塩、こしょう', amount: '', unit: '', other_amount: '各少量', post_recipe_id: post_recipes[11].id },
    {food_name: '大根', amount: '10', unit: '㎝', other_amount: '', post_recipe_id: post_recipes[12].id },
    {food_name: 'にんじん', amount: '6', unit: '㎝', other_amount: '', post_recipe_id: post_recipes[12].id },
    {food_name: 'ごぼう', amount: '20', unit: '㎝', other_amount: '', post_recipe_id: post_recipes[12].id },
    {food_name: 'こんにゃく', amount: '', unit: '枚', other_amount: '1/2', post_recipe_id: post_recipes[12].id },
    {food_name: 'サラダ油', amount: '', unit: '', other_amount: '大さじ2', post_recipe_id: post_recipes[12].id },
    {food_name: '豚こま切れ肉', amount: '300', unit: 'ℊℊ', other_amount: '', post_recipe_id: post_recipes[12].id },
    {food_name: '酒', amount: '', unit: '', other_amount: '小さじ2', post_recipe_id: post_recipes[12].id },
    {food_name: 'だし', amount: '', unit: '', other_amount: 'A:カップ6', post_recipe_id: post_recipes[12].id },
    {food_name: 'みりん', amount: '', unit: '', other_amount: 'A:少量', post_recipe_id: post_recipes[12].id },
    {food_name: 'みそ', amount: '', unit: '', other_amount: '大さじ4', post_recipe_id: post_recipes[12].id },
    {food_name: 'ねぎ（小口切り）', amount: '10', unit: '㎝', other_amount: '', post_recipe_id: post_recipes[12].id },
    {food_name: '七味唐辛子', amount: '', unit: '', other_amount: '少量', post_recipe_id: post_recipes[12].id },
    {food_name: '合いびき肉', amount: '600', unit: 'ℊ', other_amount: '', post_recipe_id: post_recipes[13].id },
    {food_name: '玉ねぎ', amount: '1', unit: '個', other_amount: '', post_recipe_id: post_recipes[13].id },
    {food_name: 'パン粉', amount: '', unit: '', other_amount: 'A：カップ2/3', post_recipe_id: post_recipes[13].id },
    {food_name: '卵', amount: '2', unit: '個', other_amount: 'A：', post_recipe_id: post_recipes[13].id },
    {food_name: '牛乳', amount: '', unit: '', other_amount: 'A：大さじ2', post_recipe_id: post_recipes[13].id },
    {food_name: '水', amount: '', unit: '', other_amount: 'B：カップ1/2', post_recipe_id: post_recipes[13].id },
    {food_name: 'トマトケチャップ', amount: '', unit: '', other_amount: 'B：大さじ6', post_recipe_id: post_recipes[13].id },
    {food_name: 'ウスターソース', amount: '', unit: '', other_amount: 'B：大さじ2', post_recipe_id: post_recipes[13].id },
    {food_name: 'しょうゆ', amount: '', unit: '', other_amount: 'B：小さじ１', post_recipe_id: post_recipes[13].id },
    {food_name: 'バター', amount: '', unit: '', other_amount: 'B：大さじ1', post_recipe_id: post_recipes[13].id },
    {food_name: 'にんじん', amount: '12', unit: '㎝', other_amount: '', post_recipe_id: post_recipes[13].id },
    {food_name: 'ブロッコリー', amount: '8～12房', unit: '', other_amount: '', post_recipe_id: post_recipes[13].id },
    {food_name: '塩', amount: '', unit: '', other_amount: '適宜', post_recipe_id: post_recipes[13].id },
    {food_name: 'サラダ油', amount: '', unit: '', other_amount: '大さじ２', post_recipe_id: post_recipes[13].id },
    {food_name: 'むきえび', amount: '240', unit: 'ℊ', other_amount: '', post_recipe_id: post_recipes[14].id },
    {food_name: 'グラタン用マカロニ', amount: '160', unit: 'ℊ', other_amount: '（9～10分ゆで）', post_recipe_id: post_recipes[14].id },
    {food_name: 'マッシュルーム', amount: '6', unit: '個', other_amount: '（100ℊ）', post_recipe_id: post_recipes[14].id },
    {food_name: '玉ねぎ', amount: '', unit: '個', other_amount: '1/2', post_recipe_id: post_recipes[14].id },
    {food_name: 'バター', amount: '40', unit: 'ℊ', other_amount: '', post_recipe_id: post_recipes[14].id },
    {food_name: '小麦粉', amount: '40', unit: 'ℊ', other_amount: '', post_recipe_id: post_recipes[14].id },
    {food_name: '水', amount: '300', unit: '㎖', other_amount: 'A:（カップ2・1/2）', post_recipe_id: post_recipes[14].id },
    {food_name: '塩', amount: '', unit: '', other_amount: 'A:小さじ1/2', post_recipe_id: post_recipes[14].id },
    {food_name: '顆粒スープの素（洋風）', amount: '', unit: '', other_amount: 'A:小さじ1/2', post_recipe_id: post_recipes[14].id },
    {food_name: 'こしょう', amount: '', unit: '', other_amount: 'A:少量', post_recipe_id: post_recipes[14].id },
    {food_name: '牛乳', amount: '300', unit: '㎖', other_amount: '（カップ1・1/2）', post_recipe_id: post_recipes[14].id },
    {food_name: 'ピザ用チーズ', amount: '100', unit: 'ℊ', other_amount: '', post_recipe_id: post_recipes[14].id }
  ]
)

PostComment.create!(
  [
    {comment: '参考にさせていただきました。ありがとうございました。', post_recipe_id: post_recipes[0].id, user_id: users[8].id },
    {comment: 'この組み合わせは間違いないですね！', post_recipe_id: post_recipes[0].id, user_id: users[9].id },
    {comment: 'ありがとうございます！いつも大根食べなかった旦那さんがこのレシピだと食べてくれます！', post_recipe_id: post_recipes[0].id, user_id: users[1].id },
    {comment: 'はじめて作りました！おいしかったです！', post_recipe_id: post_recipes[0].id, user_id: users[7].id },
    {comment: 'ご飯作るのめんどくさーい！って時に楽ちんメニューなので助かりますね！', post_recipe_id: post_recipes[1].id, user_id: users[3].id },
    {comment: '簡単！うまい！手抜き最高♥', post_recipe_id: post_recipes[1].id, user_id: users[2].id },
    {comment: 'はじめてオムレツ作りました！形は少しくずれてしまいましたが、美味しくできました！', post_recipe_id: post_recipes[4].id, user_id: users[9].id },
    {comment: 'いつもケチャップでたべるのですが、ブラックペッパー合いますね！', post_recipe_id: post_recipes[4].id, user_id: users[9].id },
    {comment: 'うまくできなかった。', post_recipe_id: post_recipes[4].id, user_id: users[5].id },
    {comment: '卵大好きなのでいつも作っています。', post_recipe_id: post_recipes[4].id, user_id: users[6].id },
    {comment: 'しっかり焼いてお弁当に入れてみました！冷めても美味しいですね。', post_recipe_id: post_recipes[4].id, user_id: users[7].id },
    {comment: 'ほどよい半熟にできました！美味しい！！！', post_recipe_id: post_recipes[4].id, user_id: users[8].id },
    {comment: '豚肉で作ったことがなかったのですが、牛肉よりもあっさりして食べやすいですね。', post_recipe_id: post_recipes[6].id, user_id: users[1].id },
    {comment: '参考にさせていただきました。美味しくできました！', post_recipe_id: post_recipes[6].id, user_id: users[3].id },
    {comment: 'うちの定番レシピになりました。', post_recipe_id: post_recipes[6].id, user_id: users[4].id }
  ]
)

Favorite.create!(
  [
    {post_recipe_id: post_recipes[0].id, user_id: users[1].id },
    {post_recipe_id: post_recipes[0].id, user_id: users[2].id },
    {post_recipe_id: post_recipes[0].id, user_id: users[3].id },
    {post_recipe_id: post_recipes[0].id, user_id: users[4].id },
    {post_recipe_id: post_recipes[1].id, user_id: users[0].id },
    {post_recipe_id: post_recipes[1].id, user_id: users[1].id },
    {post_recipe_id: post_recipes[1].id, user_id: users[2].id },
    {post_recipe_id: post_recipes[1].id, user_id: users[3].id },
    {post_recipe_id: post_recipes[1].id, user_id: users[4].id },
    {post_recipe_id: post_recipes[1].id, user_id: users[5].id },
    {post_recipe_id: post_recipes[1].id, user_id: users[6].id },
    {post_recipe_id: post_recipes[1].id, user_id: users[7].id },
    {post_recipe_id: post_recipes[1].id, user_id: users[8].id },
    {post_recipe_id: post_recipes[1].id, user_id: users[9].id },
    {post_recipe_id: post_recipes[2].id, user_id: users[1].id },
    {post_recipe_id: post_recipes[3].id, user_id: users[1].id },
    {post_recipe_id: post_recipes[3].id, user_id: users[3].id },
    {post_recipe_id: post_recipes[4].id, user_id: users[0].id },
    {post_recipe_id: post_recipes[4].id, user_id: users[1].id },
    {post_recipe_id: post_recipes[4].id, user_id: users[2].id },
    {post_recipe_id: post_recipes[4].id, user_id: users[2].id },
    {post_recipe_id: post_recipes[4].id, user_id: users[4].id },
    {post_recipe_id: post_recipes[4].id, user_id: users[5].id },
    {post_recipe_id: post_recipes[4].id, user_id: users[6].id },
    {post_recipe_id: post_recipes[4].id, user_id: users[7].id },
    {post_recipe_id: post_recipes[4].id, user_id: users[8].id },
    {post_recipe_id: post_recipes[4].id, user_id: users[9].id },
    {post_recipe_id: post_recipes[6].id, user_id: users[0].id },
    {post_recipe_id: post_recipes[6].id, user_id: users[1].id },
    {post_recipe_id: post_recipes[6].id, user_id: users[2].id },
    {post_recipe_id: post_recipes[6].id, user_id: users[3].id },
    {post_recipe_id: post_recipes[6].id, user_id: users[4].id },
    {post_recipe_id: post_recipes[6].id, user_id: users[6].id },
    {post_recipe_id: post_recipes[6].id, user_id: users[7].id },
    {post_recipe_id: post_recipes[6].id, user_id: users[8].id },
    {post_recipe_id: post_recipes[6].id, user_id: users[9].id }
  ]
)